{% set name = "sphinx-design" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/executablebooks/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c3cbcbef4a176295f146adfca5d998ff161dd2d3750ff6abac58e8df2e5e1243

build:
  number: 0
  skip: True  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - flit-core
    - pip
    - sphinx 5.0.2
  run:
    - python
    - sphinx >=5,<9

test:
  imports:
    - sphinx_design
  requires:
    - pip
    - pytest
    - defusedxml
    #- myst-parser
    #- pytest-regressions
  source_files:
    - tests/
  commands:
    - pip check
    # Skip `test_sd_hide_title_myst` and `test_sd_hide_title_rst` as the packages myst-parser and pytest-regressions package isn't available on the defaults yet
    - pytest tests -vv -k "not (test_sd_hide_title_myst or test_sd_hide_title_rst or test_octicons)"

about:
  home: https://github.com/executablebooks/sphinx-design
  dev_url: https://github.com/executablebooks/sphinx-design
  doc_url: https://sphinx-design.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A sphinx extension for designing beautiful, screen-size responsive web components
  description: |
    A sphinx extension for designing beautiful, view size responsive web components.

extra:
  recipe-maintainers:
    - awvwgk
